"""my_migrate

Revision ID: c3e8679e335b
Revises: 
Create Date: 2023-03-25 00:40:02.373006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e8679e335b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calc_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radius',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=20), nullable=False),
    sa.Column('calc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calc_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=20), nullable=False),
    sa.Column('calc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calc_id'], ['calculation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pressure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=20), nullable=False),
    sa.Column('radius_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['radius_id'], ['radius.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=20), nullable=False),
    sa.Column('radius_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['radius_id'], ['radius.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature')
    op.drop_table('pressure')
    op.drop_table('time')
    op.drop_table('radius')
    op.drop_table('calculation')
    # ### end Alembic commands ###
